### PR TITLE
Command updates

### PR DESCRIPTION
**Pull request by PetteriM1**

### CODE REVIEW

**Comment by vuahackervn** [comment]
You mvn one file nukkit.jar for newbie

**Comment by PetteriM1** [comment]
> You mvn one file nukkit.jar for newbie

Here is link to latest build: [https://505-120112332-gh.circle-artifacts.com/0/home/circleci/Nukkit-SuomiCraftPE/target/Nukkit-SuomiCraftPE.jar](https://505-120112332-gh.circle-artifacts.com/0/home/circleci/Nukkit-SuomiCraftPE/target/Nukkit-SuomiCraftPE.jar)

**Comment by esFer102** [comment]
"Artifact not found"

**Comment by PetteriM1** [comment]
> "Artifact not found"

Visit the releases page for download link (Or if you need a 1.16.100 beta build check the link in the pr)

**Pull request merged**
